[project]
name = "starbucksdb"
version = "0.1.0"
description = ""
authors = []
requires-python = "==3.13.3"
readme = "README.md"
license = "MIT"
dependencies = ["scrapy==2.13.1", "peewee==3.18.1", "colorlog==6.9.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
