name: Scrape latest data

on:
    push:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0"

jobs:
    crawl-and-update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install Poetry
              uses: abatilo/actions-poetry@v2
              with:
                  poetry-version: "1.7"

            - name: Cache poetry dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pypoetry/virtualenvs
                  key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install datasette-publish-vercel
                  poetry config virtualenvs.create false
                  poetry install

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: starbucks.db
                  path: ./data/
              continue-on-error: true

            - name: Run scrapy crawl
              run: poetry run scrapy crawl singapore

            - name: Upload updated artifact
              uses: actions/upload-artifact@v4
              with:
                  name: starbucks.db
                  path: ./data/
                  if-no-files-found: error
            - name: Deploy to vercel
              run: |-
                  datasette publish vercel data/starbucks.db \
                      --project=starbucksdb
                      --install=datasette-hashed-urls
                      --install=datasette-cluster-map
                      --token=${{ secrets.VERCEL_TOKEN }}
                      --setting allow_download off 
                      --setting allow_csv_stream off 
                      --setting max_csv_mb 0
                      --extra-options "-i"
